source 'http://rubygems.org'

gem 'rails', '>=3.0.7'
gem "mongoid", "~>2.0"
gem "bson_ext", "~> 1.3"
gem 'haml'
gem 'hpricot'
gem 'rcov'
gem 'devise'
gem 'ci_reporter', :groups => [:development, :test]
gem 'sass'
gem 'undata', ">= 0.1.1"

group :development do
  gem 'test-unit'
end