
require 'rubygems'
# Install:
#  sudo gem install ci_reporter
gem 'ci_reporter'
require 'ci/reporter/rake/test_unit' # use this if you're using Test::Unit

require File.expand_path('../config/application', __FILE__)
require 'rake'

Oliver::Application.load_tasks
